apiVersion: v1
kind: Pod
metadata:
  name: event-bus
  labels:
    app: event-bus
    rel: stable
spec:
  containers:
    - name: event-bus
      image: davechedjoun/event-bus
      ports:
        - containerPort: 4005
      resources: {}